# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 08:26
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('cameraName', models.CharField(max_length=100)),
                ('cameraId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarUser',
            fields=[
                ('vehicleType', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('mobileNumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLocation',
            fields=[
                ('lotId', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('isParked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=255)),
                ('editor', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=[], size=None)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreferredParkingLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferredParkingLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkxes.ParkingLocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkxes.CarUser')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('licensePlateNumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vehicleType', models.CharField(max_length=20)),
                ('caruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkxes.CarUser')),
            ],
        ),
        migrations.AddField(
            model_name='parkinglocation',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkxes.ParkingZone'),
        ),
        migrations.AddField(
            model_name='camera',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkxes.ParkingZone'),
        ),
    ]
